import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** Primary key: UUIDv7 generated by Postgres 18 (`uuidv7()`), so ids sort by creation time. */
export const id = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

/** Every tenant table carries this; RLS compares it with `app_tenant_id()`. */
export const tenantId = () => uuid('tenant_id').notNull();

/** UTC instant. Shown in Asia/Colombo by the apps. */
export const instant = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

/** `updated_at` is maintained by the `set_updated_at` trigger (migrations/0002), not by callers. */
export const timestamps = () => ({
  createdAt: instant('created_at').notNull().defaultNow(),
  updatedAt: instant('updated_at').notNull().defaultNow(),
});
