import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { id, instant, tenantId } from './columns';
import { invoiceLines, payments } from './fees';
import { tenants } from './tenants';
import { students, tenantUsers } from './users';

/** ADR 0009: an upload is `pending` until the media worker has processed (or rejected) it. */
export const uploadStatus = pgEnum('upload_status', ['pending', 'processed', 'rejected']);
export const uploadKind = pgEnum('upload_kind', ['slip']);
/** ADR 0008 §5; `processing` = submitted but the image is not re-encoded yet. */
export const slipStatus = pgEnum('slip_status', [
  'processing',
  'submitted',
  'approved',
  'rejected',
  'superseded',
]);

/**
 * Files a user asked to upload through a presigned PUT (ADR 0009). Keys are generated by the
 * server and always carry the tenant prefix. Unprocessed rows (and objects) are deleted after
 * 24 h; processed ones are kept with the slip they belong to.
 */
export const uploads = pgTable(
  'uploads',
  {
    id: id(),
    tenantId: tenantId().references(() => tenants.id, { onDelete: 'cascade' }),
    kind: uploadKind('kind').notNull(),
    createdBy: uuid('created_by').notNull(),
    /** Declared by the client and bound into the presigned PUT; never trusted for decoding. */
    contentType: text('content_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    /** Original object, `<tenantId>/…`. Deleted once processed. */
    objectKey: text('object_key').notNull(),
    /** Re-encoded JPEG, `<tenantId>/…`. */
    processedKey: text('processed_key'),
    status: uploadStatus('status').notNull().default('pending'),
    createdAt: instant('created_at').notNull().defaultNow(),
    processedAt: instant('processed_at'),
  },
  (t) => [
    unique('uploads_tenant_id_id_key').on(t.tenantId, t.id),
    unique('uploads_tenant_object_key').on(t.tenantId, t.objectKey),
    index('uploads_tenant_status_created_idx').on(t.tenantId, t.status, t.createdAt),
    foreignKey({
      name: 'uploads_created_by_fk',
      columns: [t.tenantId, t.createdBy],
      foreignColumns: [tenantUsers.tenantId, tenantUsers.id],
    }),
    check(
      'uploads_content_type',
      sql`${t.contentType} in ('image/jpeg', 'image/png', 'image/heic', 'image/heif')`,
    ),
    check('uploads_size', sql`${t.sizeBytes} between 1 and 5242880`),
    check('uploads_object_tenant_prefix', sql`${t.objectKey} like ${t.tenantId}::text || '/%'`),
    check(
      'uploads_processed_tenant_prefix',
      sql`${t.processedKey} is null or ${t.processedKey} like ${t.tenantId}::text || '/%'`,
    ),
    check(
      'uploads_processed_state',
      sql`(${t.status} = 'processed') = (${t.processedKey} is not null)
        and (${t.status} = 'pending') = (${t.processedAt} is null)`,
    ),
  ],
);

/** FEE-05/06: a student's bank slip for whole open months (ADR 0008 §5). */
export const bankSlips = pgTable(
  'bank_slips',
  {
    id: id(),
    tenantId: tenantId().references(() => tenants.id, { onDelete: 'cascade' }),
    studentId: uuid('student_id').notNull(),
    uploadId: uuid('upload_id').notNull(),
    status: slipStatus('status').notNull().default('processing'),
    /** As written on the slip. Approval always pays the expected open amount instead. */
    amountCents: bigint('amount_cents', { mode: 'number' }).notNull(),
    reference: text('reference').notNull(),
    /** Upper-case, no whitespace: the duplicate check key (rule 4). */
    referenceNorm: text('reference_norm').notNull(),
    slipDate: date('slip_date').notNull(),
    submittedAt: instant('submitted_at').notNull().defaultNow(),
    reviewedBy: uuid('reviewed_by'),
    reviewedAt: instant('reviewed_at'),
    rejectReason: text('reject_reason'),
    paymentId: uuid('payment_id'),
    /** Approved although "Reference used before" was shown (audited). */
    duplicateConfirmed: boolean('duplicate_confirmed').notNull().default(false),
  },
  (t) => [
    unique('bank_slips_tenant_id_id_key').on(t.tenantId, t.id),
    unique('bank_slips_tenant_upload_key').on(t.tenantId, t.uploadId),
    unique('bank_slips_tenant_payment_key').on(t.tenantId, t.paymentId),
    index('bank_slips_tenant_status_submitted_idx').on(t.tenantId, t.status, t.submittedAt),
    index('bank_slips_tenant_student_submitted_idx').on(t.tenantId, t.studentId, t.submittedAt),
    index('bank_slips_tenant_reference_idx').on(t.tenantId, t.referenceNorm, t.amountCents),
    foreignKey({
      name: 'bank_slips_student_fk',
      columns: [t.tenantId, t.studentId],
      foreignColumns: [students.tenantId, students.userId],
    }),
    foreignKey({
      name: 'bank_slips_upload_fk',
      columns: [t.tenantId, t.uploadId],
      foreignColumns: [uploads.tenantId, uploads.id],
    }),
    foreignKey({
      name: 'bank_slips_reviewed_by_fk',
      columns: [t.tenantId, t.reviewedBy],
      foreignColumns: [tenantUsers.tenantId, tenantUsers.id],
    }),
    foreignKey({
      name: 'bank_slips_payment_fk',
      columns: [t.tenantId, t.paymentId],
      foreignColumns: [payments.tenantId, payments.id],
    }),
    check('bank_slips_amount_safe', sql`${t.amountCents} between 1 and 9007199254740991`),
    check('bank_slips_reference_length', sql`char_length(${t.reference}) between 3 and 40`),
    check(
      'bank_slips_reference_norm',
      sql`${t.referenceNorm} = upper(regexp_replace(${t.reference}, '\\s', '', 'g'))`,
    ),
    check(
      'bank_slips_review_state',
      sql`(${t.status} = 'approved') = (${t.paymentId} is not null)
        and (${t.status} = 'rejected') = (${t.rejectReason} is not null)
        and (${t.rejectReason} is null or char_length(${t.rejectReason}) between 3 and 200)
        and (${t.reviewedBy} is null or ${t.reviewedAt} is not null)
        and (${t.status} not in ('approved', 'rejected') or ${t.reviewedAt} is not null)
        and (${t.status} = 'approved' or not ${t.duplicateConfirmed})`,
    ),
  ],
);

/** The months a slip pays (slip ↔ invoice line links); fixed at submission. */
export const bankSlipLines = pgTable(
  'bank_slip_lines',
  {
    id: id(),
    tenantId: tenantId().references(() => tenants.id, { onDelete: 'cascade' }),
    slipId: uuid('slip_id').notNull(),
    invoiceLineId: uuid('invoice_line_id').notNull(),
  },
  (t) => [
    unique('bank_slip_lines_tenant_id_id_key').on(t.tenantId, t.id),
    unique('bank_slip_lines_tenant_slip_line_key').on(t.tenantId, t.slipId, t.invoiceLineId),
    index('bank_slip_lines_tenant_line_idx').on(t.tenantId, t.invoiceLineId),
    foreignKey({
      name: 'bank_slip_lines_slip_fk',
      columns: [t.tenantId, t.slipId],
      foreignColumns: [bankSlips.tenantId, bankSlips.id],
    }),
    foreignKey({
      name: 'bank_slip_lines_line_fk',
      columns: [t.tenantId, t.invoiceLineId],
      foreignColumns: [invoiceLines.tenantId, invoiceLines.id],
    }),
  ],
);
